services:
  - type: redis
    name: broker
    plan: free
    ipAllowList: []

  - type: worker
    name: producer
    env: docker
    dockerfilePath: ./producer/Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          name: broker
          type: redis
          property: host

  - type: worker
    name: consumer
    env: docker
    dockerfilePath: ./consumer/Dockerfile
    envVars:
      - key: REDIS_HOST
        fromService:
          name: broker
          type: redis
          property: host